CREATE TABLE endereco(
endId BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
logadouro VARCHAR(50)NOT NULL,
cep VARCHAR(20) NOT NULL,
numero VARCHAR(50) NOT NULL,
cidade VARCHAR(50)NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8;